---
apiVersion: v1
kind: Service
metadata:
  name: safeconfig-backend-svc
  namespace: safeconfig-agent
spec:
  selector:
    app: safeconfig-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
