---
apiVersion: v1
kind: Service
metadata:
  name: gitguardian-backend-svc
  namespace: gitguardian-agent
spec:
  selector:
    app: gitguardian-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
