import { UserRole, EnvironmentName } from "@/lib/constants";

/**
 * 👤 User Identity & RBAC
 * Maps to the 'users' table. Used for session management and gating 'Override' buttons.
 */
export interface User {
  id: number;
  email: string;
  username: string;
  role: UserRole; // 'manager' | 'developer'
  avatar_url?: string;
  created_at: string;
}

/**
 * 🌍 Deployment Environment
 * Maps to the 'environments' table. 
 * Critical for the multi-stage (Dev -> Staging -> Prod) demo flow.
 */
export interface Environment {
  id: number;
  name: EnvironmentName;
  description?: string;
}

/**
 * 🚩 Feature Flag Core
 * The central entity for feature management. 
 * Includes nested statuses to prevent multiple API round-trips.
 */
export interface FeatureFlag {
  id: number;
  name: string;
  key: string;
  description: string;
  created_by?: string;
  statuses: FlagStatus[];
}

/**
 * ⚡ Flag Status per Environment
 * Represents the 'Live' state of a feature key in a specific infrastructure node.
 */
export interface FlagStatus {
  id: number;
  environment_id: number;
  environment_name: EnvironmentName;
  is_enabled: boolean;
  updated_at: string;
  last_updated_by?: string;
}

/**
 * 🛡️ AI Risk Assessment Report
 * The core 'Governance' artifact generated by Claude 3.5 Sonnet.
 * This is the 'Pre-flight' check that prevents catastrophic config changes.
 */
export interface AIAssessment {
  risk_score: number; // 0-10 (10 being critical 'Blast Radius')
  risk_level: "low" | "medium" | "high";
  advice: string;
  reasoning: string; // Added: For the 'Why' in the Audit Ledger
  status: "PASSED" | "BLOCKED" | "WARNING";
  requires_override: boolean;
  triggered_by: string; // The user who initiated the toggle
  blast_radius_hits: number; // Real-time Redis impact data
  sustainability_audit?: SustainabilityReport;
}

/**
 * 🍃 Green Audit (Gemini 1.5 Flash)
 * Specifically targets the $3,000 'Sustainability' Prize Category.
 * Analyzes the compute/energy impact of a feature rollout.
 */
export interface SustainabilityReport {
  efficiency_score: number; // 0-100
  carbon_impact_estimate: string;
  warnings: string[];
  green_advice: string;
}

/**
 * 📜 Compliance Ledger Entry
 * The 'Truth' of the system. Every AI decision and Manager override is here.
 * Essential for the $10,000 Grand Prize (Security & Governance).
 */
export interface AuditLog {
  id: number;
  flag_id?: number;
  flag_key: string; // Added: For easier table rendering without joins
  env_name: string;
  action: "ENABLE" | "DISABLE" | "CREATE" | "DELETE" | "OVERRIDE"; 
  reason: string; // User-provided justification
  ai_report: AIAssessment | null;
  timestamp: string;
}

/**
 * 📊 Traffic Telemetry
 * Real-time hit counts pulled from Redis.
 */
export interface TrafficStats {
  key: string; 
  hit_count: number;
  last_hit: string;
}