import axios from "axios";

/**
 * 🛰️ SafeConfig AI API Client
 * Purpose: Centralized Axios instance for communicating with the Flask backend.
 * Features: Automatic Session Sync (Cookies), 401 Interception, and CORS Handshaking.
 */
export const api = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_URL,
  
  // 🛡️ CRITICAL: This allows the browser to send/receive the 'session' cookie 
  // generated by Flask-Dance and Flask-Login. Without this, auth will fail.
  withCredentials: true, 
  
  headers: {
    "Content-Type": "application/json",
    // 🏷️ Identify requests coming from the Dashboard for the Audit logs
    "X-SafeConfig-Source": "SafeConfig-Dashboard-v1",
  },
});

/**
 * 🚦 Response Interceptor
 * Purpose: Global error handling for unauthorized sessions.
 * Behavior: If the Flask backend returns 401 (Session Expired), bounce to /login.
 */
api.interceptors.response.use(
  (response) => response,
  (error) => {
    // 1. Check if the error is a 401 (Unauthorized)
    const isUnauthorized = error.response?.status === 401;
    
    // 2. Determine if we are already on the login page to avoid infinite loops
    const isLoginPage = typeof window !== "undefined" && window.location.pathname === "/login";

    if (isUnauthorized && !isLoginPage) {
      // 🛡️ Session has expired or the user was logged out. 
      // We clear the local session by forcing a redirect to the login page.
      console.warn("🔐 Session Expired or Unauthorized. Redirecting...");
      
      if (typeof window !== "undefined") {
        window.location.href = "/login";
      }
    }

    // Pass the error through so individual components can still handle specific logic
    return Promise.reject(error);
  }
);